### ISSUE TITLE
ckpt2json doesn't work well with */adam_m and */adam_v?

### ISSUE THREAD

**Issue by junpei-n** [chengchingwen/Transformers.jl#33]
The function ckpt2bson may not work well; it might set "/adam_m" or "/adam_v" to dense layers and others., because some tensorflow check point data of BERT include entities ending with "/adam_m" or "/adam_v".

Thus, I suggest that functions recognize and deal with "/adam_m" or "/adam_v".

### _Suggestions_
> **1. Change 2 functions
> _readckpt_ to transpose weights containing "/adam_m" or "/adam_v"
> _load_bert_from_tfbson_ to ignore _weights_ containing "/adam_m" or "adam_v"**
```
function readckpt(path)
...
      if length(shape) == 2 && !occursin("cls/seq_relationship/output_weights" , name) **# HERE**
        weight = collect(weight')
      end
...

function load_bert_from_tfbson(config, weights)
...
    #tf namespace handling
    weights = filter(x -> !occursin(r"/adam_[mv]", x.first), weights)  **# HERE**
    vnames = keys(weights)
...
end
```

> **2. Change function _readckpt_ to continue for-loop when name contains "/adam_m" or "/adam_v"**
> this cannot output raw ckpt because "/adam_m" and "/adam_v" are removed from _weights_
```
function readckpt(path)
....
    for (name, shape) ∈ shapes
        occursin(r"/adam_[mv]", name) && continue  **# HERE**
        weight = ckpt.get_tensor(name)
...
```

**Comment by chengchingwen** [comment]
Yes, that's a potential problem of that `ckpt2bson` function. However, currently I don't plan to update it and probably will deprecate it in the future since TensorFlow.jl isn't maintained anymore. OTOH pytorch has a format which is easier to parse and huggingface/transformers also provide some functionality to convert a tensorflow checkpoint to pytorch format. Therefore, I will focus on handling pytorch format in the future. 

But if you still need that function, you can make a PR. The second way will be better.

**Comment by junpei-n** [comment]
Thank you for your quick response. I understand why you don't fix that function.If I need to use the function, I will try to make a PR.
Thanks.
