### ISSUE TITLE
Is target masking aligned correctly for loss function

### ISSUE THREAD

**Issue by mboedigh** [chengchingwen/Transformers.jl#4]
In 1-model.jl loglkdivergence gets called with masking that does not mask out all padding tokens in the target sequence

for example, if I have a target sequence, t, with 2 for the start token, 3 for the end token and 1 for padding) and an predicted sequence p, along with target mask m
`t = 2 a b c 3 1 1`
`m = 1 1 1 1 1 0 0`
`p = a b c 3 a a a`

loglkdivergence gets called with t[2:end], m[1:end-1], p[1:end-1], which aligns like this
`t =  a b c 3 1 1`
`m = 1 1 1 1 1 0 `
`p = a b c 3 a a`

It would appear that the first predicted character past the end token is penalized, because it is not masked out. But should it be, since it corresponds to no character in the target?

**Comment by chengchingwen** [comment]
Thanks for the issue! You are right, that was a mistake. The mask should go with `[2:end]` like the target does. However, this should not influence the result much since we never need the prediction after end token in the test time. Still, thanks for pointing this out, I would update the example later.
